# 6. 패키지 (package)

- 특정 목적을 수행하는 모듈을 모아높은 집합체
- 모듈을 계층적인 구조로 관리하기 위해 사용
- 매우 복잡하고 다양한 기능이 수행되는 경우, 많은 모듈이 필요하며, 이를 패키지로 쉽게 다룰 수 있음

In [15]:
# package1 폴더에 있는 modul1.py 파일, 모듈을 호출하여 사용
from package1 import modul1

modul1.fibo(40)

102334155

In [18]:
modul1.fast_fibo(40)

102334155

In [2]:
# 초기화 폴더 __init__.py
import package1
package1.pack_version()

package version : 1.0


## 6-1. 기타 파이썬 내장 함수 및 표준 라이브러리

- 라이브러리 : 특정 프로그래밍 목적을 수행하기 위한 모듈 또는 패키지의 집합체
- 표준 라이브러리 : 파이썬 내에 직접 사용이 가능한 함수 또는 모듈 / 패키지
    - 간단한 과학, 통계연산, 데이터처리, 파일불러오기 등
    - 약 50여가지의 내장 함수가 존재
    
- 외장 라이브러리의 경우 추가적으로 다운로드 받아서 사용

In [3]:
# 절대값 반환
abs(-100)

100

In [4]:
# 특정 데이터 값을 정렬하는 함수 (리스트, 튜플, 셋 사용 가능)
t1 = (10, 2000, 30, 20, 3, 1, 5)
sorted(t1)

[1, 3, 5, 10, 20, 30, 2000]

In [5]:
sorted(t1, reverse = True)

[2000, 30, 20, 10, 5, 3, 1]

In [6]:
# 특정 개체가 가진 변수나 함수, 기능들을 확인하는 함수
dir([10, 20]) # 리스트 자료구조 내에서 사용할 수 있는 함수들을 모두 확인 가능

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [11]:
# 자료구조 내 값을 순서와 값으로 나누어 연산
index_list = []
value_list = []
for i, data in enumerate(['A', 'B', 'C', 'D']):
    index_list.append(i)
    value_list.append(data)
    
index_list

[0, 1, 2, 3]

In [13]:
value_list

['A', 'B', 'C', 'D']

In [24]:
# 시간 관련 표준 라이브러리
# 현장에서 데이터분석에 중요한 타입 중 하나가 시간에 대한 데이터 타입
import datetime
start_time = datetime.datetime.today() # 현재 시스템 상 시간
end_time = datetime.datetime(2025, 3, 24) # 특정 원하는 날짜를 지정

In [25]:
start_time - end_time

datetime.timedelta(days=3, seconds=36787, microseconds=327374)

In [26]:
start_time.weekday() # 요일 : 0-월, 1-화, 2-수, ... 

3

In [27]:
import time
time.time() # UTC (universal time coordinated, 협정 세계 표준시)를 사용
# 1970년 1월 1일 0시 0분 0초를 기준으로 현재까지 몇 초가 흘렀는지 계산

1743038208.1325355

In [28]:
time.localtime(time.time()) # 

time.struct_time(tm_year=2025, tm_mon=3, tm_mday=27, tm_hour=10, tm_min=17, tm_sec=1, tm_wday=3, tm_yday=86, tm_isdst=0)

In [29]:
# 코드에 일정한 시간 간격을 두고 코드를 수행
t1 = time.time()
time.sleep(10)
t2 = time.time()

t2 - t1

10.001246213912964

In [30]:
# 난수 생성과 관련한 라이브러리
import random
random.random() # 0과 1 사이의 수에서 난수를 생성

0.42851071952394915

In [31]:
random.randint(1, 100) # 특정 범위의 정수 내에서 난수를 생성

62

In [37]:
l = [0 for _ in range(10)]
for _ in range(1000):
    l[random.randint(0, 9)] += 1
    
print(l)

[111, 94, 89, 98, 98, 110, 110, 93, 94, 103]


In [35]:
# 수학 관련 함수를 쓸 수 있는 라이브러리
import math
math.lcm(20, 30) # 두 수의 최소공배수를 계산
math.gcd(20, 30) # 최대 공약수
math.factorial(5) # 팩토리얼

120

## 6-3. 정규표현식

- 정규표현식(regualer expression)은 문자열을 처리할 때 특정 패턴을 정의하는데 사용 되는 문자열
- 문자열 패턴을 사용하여, 문자열 검색, 대체, 추출 작업등을 수행
- 정규표현식은 특정 규칙을 가지고 있어, 다양한 문자와 연산자를 조합하여 복잡한 문자 패턴을 표현
- 크롤링 또는 자연어처리에서 데이터의 특정 패턴을 찾거나 추출할 때 사용

**메타문자 (meta characters)**
- 문자가 가진 원래 의미가 아닌 특별한 용도로 사용되는 문자
- 정규표현식에서는 대괄호 [] 안에 포함된 문자들 중 하나와 매치를 뜻함

In [38]:
# . ^ $ +
import re
# 대괄호 [] : 대괄호 내 포함된 문자들 중 하나와 매칭되는지 확인
pattern = r'[abc]' # raw string -> r : 문자열 내에 매타 문자가 포함되어 있다
text1 = 'apple is 사과'
re.findall(pattern, text1)

['a']

In [39]:
pattern = r'[a-z]' # [] 내 두 문자 사이에 - 기호를 사용하면, 두 문자 사이의 범위를 지정
re.findall(pattern, text1) # 문자열 전체에서 패턴과 일치하는 모든 부분을 찾아 리스트로 변환

['a', 'p', 'p', 'l', 'e', 'i', 's']

In [40]:
pattern = r'[가-힣]'
text2 = "so you don't cry for me 세월 지나도 난 변하지 않아 ~"
re.findall(pattern, text2)

['세', '월', '지', '나', '도', '난', '변', '하', '지', '않', '아']

In [42]:
pattern = r'[가-힣]+' # + : 공백을 기준으로 문자의 패턴을 확인
re.findall(pattern, text2)

['세월', '지나도', '난', '변하지', '않아']

In [43]:
# ^ : 해당 문자열을 제외한 나머지 패턴을 확인
pattern = r'[^가-힣]+'
re.findall(pattern, text2)

["so you don't cry for me ", ' ', ' ', ' ', ' ', ' ~']

In [45]:
pattern = r'[a-zA-Z]+'
re.findall(pattern, text2)

['so', 'you', 'don', 't', 'cry', 'for', 'me']

In [46]:
pattern = r'\d+' # 모든 숫자
text3 = '1초라도 안보이면, 2이렇게 초조한데'
re.findall(pattern, text3)

['1', '2']

In [47]:
# 소괄호는 특정 패턴 앞이나 뒤의 값을 확인
pattern = r'(\d+)\원'
text4 = '2000원 짜리 아이스크림 4개 주세요. 500원 잔돈입니다.'
re.findall(pattern, text4)

['2000', '500']

In [48]:
# re.sub( ) : 패턴과 일치하는 모든 부분을 다른 문자로 대치
text5 = "그댄 나의 챔피언 너와 나의 챔피언 우리 함께 외치면 승리하리라 한국"
pattern = r'챔피언'
replace_pattern = '챔피폰~'

re.sub(pattern, replace_pattern, text5)

'그댄 나의 챔피폰~ 너와 나의 챔피폰~ 우리 함께 외치면 승리하리라 한국'

In [49]:
# re.split() : 특정 패턴을 기준으로 문자를 분할
pattern = r'\W+' # \W : 비단어 문자
re.split(pattern, text5)

['그댄', '나의', '챔피언', '너와', '나의', '챔피언', '우리', '함께', '외치면', '승리하리라', '한국']

# 미니미션

1. 하나의 리스트를 입력 받았을 때, 중복을 제거하여 출력하는 함수를 만드시오.
2. 무작위로 입력받은 튜플을 오름차순으로 정렬하는 함수를 만드시오.
3. 1부터 45까지의 6개의 숫자를 중복없이 임의로 추천해주는 번호 생성 함수를 만드시오.
4. 숫자를 입력받아 해당 숫자가 홀수인지, 짝수인지 판별하는 프로그램을 if문 없이 만드시오.
5. 1부터 30까지 숫자 중 홀수만을 갖는 리스트를 리스트컴프리헨션을 이용해 생성하시오.

In [63]:
import random

# 1번 문제
def first(l):
    return list(set(l))

# 2번 문제
def second(t):
    return tuple(sorted(t))

# 3번 문제
def third():
    stack = set()
    while len(stack) != 6:
        stack.add(random.randint(1, 45))
    return stack
        
# 4번 문제
def fourth(num):
    diff = num % 2
    dic = {1:"홀수", 0:"짝수"}
    return f"입력된 숫자는 {dic[diff]}입니다."
    
# 5번 문제
def fifth():
    return [i for i in range(1, 31) if i % 2 == 1]


# 7. 데이터 분석 라이브러리

- 라이브러리 : 특정 프로그래밍의 목적을 달성하기 위한 함수들의 집합체
- 데이터 분석을 위한 라이브러리 종류
    - numpy (numeric python) : 연속형 자료에 대한 과학, 통계, 수학 연산 관련 함수들의 집합
    - pandas (panel dataset) : 정형데이터(execl, csv, sql, ...)를 처리, 분석, 통계 연산 함수들의 집합
    - matplotlib (matlab plot library) : 연속형 자료들의 그래프를 시각화 하는 함수들의 집합
    - seaborn : 정형데이터의 통계적 연산 및 시각화
    - plotly : 정형데이터의 시각화 (동적 시각화)
    - scipy (science python) : 응용통계(가설 검정, 회귀 분석, 시계열 분석) 함수들의 집합
    - scikit-learn (science python learning toolkit) : 정형데이터에서 기계학습(데이터 마이닝) 함수들의 집합
    - tensorflow (tensor flow) : 비정형데이터 처리 및 신경망 알고리즘(딥러닝) 함수들 집합
    - keras : 신경망 알고리즘 함수들의 집합
    - pytorch : 비정형 데이터 처리, 딥러닝, ...
    - request : 웹으로 부터 정보를 주고 받거나 추출할 때 사용
    - bs4 : 웹 기반(HTML)형식의 자료를 분해하여 정보를 추출할 때 사용
    - selenium : 프로그램이나 어플리케이션의 진단 및 자동화, 크롤링 사용

# 7-1. Numpy

In [64]:
# 라이브러리 호출
import numpy as np # as : 특정 패키지나 라이브러리의 이름을 줄여 사용
data1 = [6, 2, 3, 1, 2, 4, 5] # 일반적인 파이썬 리스트 자료구조
sum(data1)

23

In [65]:
# numpy 라이브러리에서 통계량을 쉽게 계산
# numpy 라이브러리 내에 있는 자료구조로 데이터를 선언
data2 = np.array(data1) # 배열 자료구조로 변환
type(data2)

numpy.ndarray

In [66]:
print(data2.mean())
print(data2.min())
print(data2.max())

3.2857142857142856
1
6


In [67]:
[x for x in range(1, 11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [68]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
np.arange(10, dtype = 'float')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [70]:
np.arange(2, 10, dtype = 'float')

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [71]:
np.arange(10, 11, 0.1) # 특정 간격을 두고 데이터를 생성

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

In [73]:
# 특정 간격 내 데이터의 갯수를 지정하여 array 구성하는 함수
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [74]:
data3 = np.linspace(100, 200, 10)
data3.ndim # 데이터의 차원 수를 표현 scalar: 0, vector: 1, matrix: 2, 3-tensor 3, ...

1

In [75]:
# 자료구조의 matrix 행렬 표현
v1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(v1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
# Matrix 간 연산
data5 = np.array([[1, 2], [3, 4], [5, 6]])
data6 = np.array([[10, 10], [1, 1], [100, 100]])
data5 + data6 # 각 행렬 위치에 존재하는 성분들이 합해진다

array([[ 11,  12],
       [  4,   5],
       [105, 106]])

In [77]:
# matrix 자료에 대한 indexing
data7 = np.array([['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']])
data7.shape

(3, 3)

In [78]:
data7 # U1: 한 글자로 되어 있는 문자열 (<U2: 두 글자, <U3 세글자, ...)

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I']], dtype='<U1')

In [79]:
# 행(row)을 기준으로 데이터를 indexing
data7[0]

array(['A', 'B', 'C'], dtype='<U1')

In [81]:
# 열(columns)을 기준으로 데이터를 indexing
data7[:2, 0]

array(['A', 'D'], dtype='<U1')

In [82]:
data7[:, 0] # 0번째에 해당하는 열 정보를 모두 indexing

array(['A', 'D', 'G'], dtype='<U1')

In [84]:
# 기존의 matrix에 새로운 행 정보를 추가
np.vstack([data7, ['j', 'k', 'l']])

array([['A', 'B', 'C'],
       ['D', 'E', 'F'],
       ['G', 'H', 'I'],
       ['j', 'k', 'l']], dtype='<U1')

In [85]:
np.hstack([data7, [['m'], ['n'], ['o']]])

array([['A', 'B', 'C', 'm'],
       ['D', 'E', 'F', 'n'],
       ['G', 'H', 'I', 'o']], dtype='<U1')

In [86]:
# 특정 행 정보를 변경
data7[1] = ['Z', 'X', 'Y']
data7

array([['A', 'B', 'C'],
       ['Z', 'X', 'Y'],
       ['G', 'H', 'I']], dtype='<U1')

In [88]:
data7[0, 1] = 'K'
data7

array([['A', 'K', 'C'],
       ['Z', 'X', 'Y'],
       ['G', 'H', 'I']], dtype='<U1')

In [89]:
# 재구조화 (행렬의 구조를 변화)
data8 = np.array([10, 20, 30, 40])
data8.reshape(4, 1)

array([[10],
       [20],
       [30],
       [40]])

In [90]:
data9 = np.linspace(1, 100, 10)
data9.reshape(-1, 1) # 1 * 10 -> 10 * 1 변환

array([[  1.],
       [ 12.],
       [ 23.],
       [ 34.],
       [ 45.],
       [ 56.],
       [ 67.],
       [ 78.],
       [ 89.],
       [100.]])

In [91]:
data9.sum()

505.0

In [95]:
data5.sum(axis = 1) # 행단위로 계싼

array([ 3,  7, 11])

1. 1부터 30까지 숫자 중에서 3의 배수이지만 4의 배수는 아닌 숫자를 출력하는 프로그램을 함수로 구성하시오.
2. 1부터 15까지의 범위의 숫자 중 5개를 선택했을 때, 나올 수 있는 모든 경우의 수를 계산하시오.
    - 단, 중복을 제외하여 계산
    - (1,2,3,4,5)와 (1,3,2,4,5)는 같은 조합으로 계산
3. 두 숫자를 입력받아 큰 숫자를 반환하는 람다 함수를 작성하세요.
4. 아래 두 개의 리스트에서 중복된 값을 제거하여 출력하는 함수를 구성하시오.
    - list1 = [100,200,300,400,500,600]
    - list2 = [200,400,600,800,1000]
    - 결과 : [100,200,300,400,500,600,800,1000]
5. 사용자가 1에서 50사이의 숫자를 선택했을 때, 컴퓨터가 임의로 생성한 수를 맞추는 프로그램을 구성하고자 한다.
아래의 조건에 맞춰 프로그램을 제작하시오.
    - 1. 컴퓨터는 1에서 50사이의 정수를 생성
    - 2. 사용자는 컴퓨터가 생성한 숫자를 맞추기 위해, 숫자를 입력
    - 3. 사용자가 입력한 숫자가 맞다면, "정답입니다"를 출력
    - 4. 사용자가 입력한 숫자가 틀리다면, "오답입니다"를 출력하고, 다시 입력받을 수 있도록 구성
6. 프로그래머스 풀기

In [109]:
from itertools import combinations
import random

def first():
    ans = []
    for num in range(1, 31):
        if num % 3 == 0 and num % 4 != 0:
            ans.append(num)
    return ans

def second():
    print(len(list(combinations(range(1, 16), 5))))
    
third = lambda x, y: max(x, y)

def fourth(list1, list2):
    return sorted(set(list1 + list2))

def fifth():
    computer = random.randint(1, 50)
    while True:
        people = int(input())
        if computer == people:
            print("정답입니다")
            break
        else:
            print("오답입니다")